name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "6699ce61-13a9-4e2d-af0c-b01bcea7d71d" | docker login -u "alexyang1982" --password-stdin
        docker image build -t alexyang1982/gitops:hellov1.2 .
        docker push alexyang1982/gitops:hellov1.2
